### ISSUE TITLE
Add absolute lower value

### ISSUE THREAD

**Issue by KronosTheLate** [halleysfifthinc/Peaks.jl#27]
Again, this is not hard to implement manually. But it would be very nice to be able to specify a lower bound for not only the peak prominence, but also the absolute value.

**Comment by halleysfifthinc** [comment]
Thanks for your interest! I'm not clear on what exactly you mean, do you mean only keeping peaks that are (absolutely) larger than a given value? Otherwise, you might already be able to accomplish what you want using the `minheight` and `maxheight` kwargs in the `peakheights` function? Can you give an example?

**Comment by KronosTheLate** [comment]
I can see this is completely a discoverability issue. Nice to see that the option is there! I thought the README was the main documentation, and that every filtering option was shown in the plot. I can however see that it is indeed in the docs.

Might I suggest that a) all functions are shown in the readme, or that b) the readme is made more barebones, and that users are referred to the documentation for fuller examples, which should include examples using `peakheight`?
